---

- name: devops
  hosts: all
  become: yes
  
 #Roles 
  roles:
    - logstash
    - apt
    - ntp
    - monit
    - java
    - elasticsearch
            
  vars:
#Elasticsearch settings
    elasticsearch_plugins:
    - name: royrusso/elasticsearch-HQ/v1.0.0  
    - name: mobz/elasticsearch-head
    - name: elasticsearch/elasticsearch-cloud-aws/2.4.2
     

 #Tasks      
  tasks:
    - name: id
      shell: ps -e | grep "VBox" | awk 'NR==1{print $1}'
      register: unique_id

    - name: ini file
      ini_file: 
        dest: /etc/conf
        section: general 
        option: uniqueID 
        value: "{{unique_id.stdout}}" 
        mode: 0600
